-- SAPBWKCRM.AAI_AAT_MAXSEQ
--
-- ENHC2008944 added LIMITED_SUBMISSION_OPPORTUNITY as the last column (38),
-- VARCHAR2(1). The view is a UNION of two branches and the column is last in
-- both, joined on AWARD_ID in each:
--
--   branch 1   LEFT JOIN SAPBWKCRM.AWARD_CUSTOM_DATA CUSTOM ON CUSTOM.AWARD_ID = R.AWARD_ID
--   branch 2   LEFT JOIN SAPBWKCRM.AWARD_CUSTOM_DATA CUSTOM ON CUSTOM.AWARD_ID = P.AWARD_ID
--
-- Two things to know before touching this view:
--
-- 1. It is UNION, not UNION ALL. Leave it that way. UNION deduplicates, so a
--    new column can change the row count by splitting rows that used to be
--    identical. This column cannot, because it is functionally dependent on
--    AWARD_ID and both branches already select AWARD_ID.
--
-- 2. Branch 1 columns are qualified with R. AWARD_CUSTOM_DATA also has an
--    AWARD_ID, so an unqualified AWARD_ID in branch 1 gives ORA-00918 once
--    CUSTOM is in scope.
--
-- Join on AWARD_ID, never AWARD_NUMBER. AWARD_CUSTOM_DATA has no AWARD_NUMBER
-- column, and an award number covers many award versions - 249,970 custom-data
-- AWARD_IDs across 43,483 award numbers, worst case 545 to one.
--
-- The 2026-09-11 deploy reformatted the whole view and dropped twelve inline
-- comments that used to be here - see the README, "Comments we lost".
--
-- This is the deployed production text, read from DBA_VIEWS on 2026-09-11.
-- Everything below the CREATE line is verbatim. Do not reformat it.

CREATE OR REPLACE VIEW SAPBWKCRM.AAI_AAT_MAXSEQ AS
WITH TEMP_TAB AS
(
    SELECT
        AWARD_NUMBER,
        CLOSING_TRANS_CD,
        MIN(TRANSACTION_ID) AS TRANSACTION_ID,
        RANK() OVER (
            PARTITION BY AWARD_NUMBER
            ORDER BY CLOSING_TRANS_CD
        ) AS SET_NUMBER
    FROM
    (
        SELECT
            Y.AWARD_NUMBER,
            Y.TRANSACTION_ID,
            Y.SEQUENCE_NUMBER,
            CASE
                WHEN Y.TRANSACTION_TYPE_CODE = 1
                THEN SAPBWKCRM.GET_END_TRAN_ID(
                    Y.AWARD_NUMBER,
                    Y.TRANSACTION_ID
                )
                ELSE 0
            END AS CLOSING_TRANS_CD
        FROM SAPBWKCRM.AAI_AAT_MAXSEQ_ROLLUP Y
    )
    WHERE CLOSING_TRANS_CD != 0
    GROUP BY
        AWARD_NUMBER,
        CLOSING_TRANS_CD
),

TEMP_TAB_S AS
(
    SELECT
        AWARD_NUMBER,
        TO_CHAR(FINAL_EXPIRATION_DATE, 'YYYYMMDD') AS FINAL_EXP_DATE,
        OBLIGATED_TOTAL_DIRECT,
        OBLIGATED_TOTAL_INDIRECT,
        AMOUNT_OBLIGATED_TO_DATE
    FROM
    (
        SELECT
            X.FINAL_EXPIRATION_DATE,
            X.OBLIGATED_TOTAL_DIRECT,
            X.OBLIGATED_TOTAL_INDIRECT,
            X.AMOUNT_OBLIGATED_TO_DATE,
            X.AWARD_NUMBER,
            X.SEQUENCE_NUMBER,
            X.AWARD_AMOUNT_INFO_ID,
            MAX(X.AWARD_AMOUNT_INFO_ID) OVER (
                PARTITION BY X.AWARD_NUMBER,
                             X.SEQUENCE_NUMBER
            ) AS MAX_AWARD_AMOUNT_INFO_ID,
            MAX(X.SEQUENCE_NUMBER) OVER (
                PARTITION BY X.AWARD_NUMBER
            ) AS MAX_SEQUENCE_NUMBER
        FROM KCOEUS.AWARD_AMOUNT_INFO X
    )
    WHERE SEQUENCE_NUMBER = MAX_SEQUENCE_NUMBER
      AND AWARD_AMOUNT_INFO_ID = MAX_AWARD_AMOUNT_INFO_ID
),

TEMP_TAB_TRAN_ID AS
(
    SELECT
        P.AWARD_NUMBER,
        P.TRANSACTION_ID
    FROM SAPBWKCRM.AAI_AAT_MAXSEQ_ROLLUP P
    JOIN TEMP_TAB Q
      ON P.AWARD_NUMBER = Q.AWARD_NUMBER
     AND P.TRANSACTION_ID BETWEEN Q.TRANSACTION_ID
                              AND Q.CLOSING_TRANS_CD
)

SELECT
    R.ANTICIPATED_CHANGE_DIRECT,
    R.ANTICIPATED_CHANGE_INDIRECT,
    R.ANTICIPATED_TOTAL_DIRECT,
    R.ANTICIPATED_TOTAL_INDIRECT,
    S.OBLIGATED_TOTAL_DIRECT,
    S.OBLIGATED_TOTAL_INDIRECT,
    R.VER_NBR,
    R.TNM_DOCUMENT_NUMBER,
    R.AWARD_AMOUNT_INFO_ID,
    R.AWARD_ID,
    R.AWARD_NUMBER,
    R.SEQUENCE_NUMBER,
    R.ANTICIPATED_TOTAL_AMOUNT,
    R.ANT_DISTRIBUTABLE_AMOUNT,
    R.OBLI_DISTRIBUTABLE_AMOUNT,
    R.TRANSACTION_ID,
    R.ENTRY_TYPE,
    R.EOM_PROCESS_FLAG,
    R.UPDATE_USER,
    R.ANTICIPATED_CHANGE,
    R.OBLIGATED_CHANGE,
    R.OBLIGATED_CHANGE_DIRECT,
    R.OBLIGATED_CHANGE_INDIRECT,
    R.OBJ_ID,
    R.ORIGINATING_AWARD_VERSION,
    S.AMOUNT_OBLIGATED_TO_DATE,
    S.FINAL_EXP_DATE,
    R.CUR_FUND_EFEC_DATE,
    R.OBLI_EXP_DATE,
    R.UPDATE_TIMESTAMP,
    R.TRANSACTION_TYPE_CODE,
    R.TNMCREATEDON,
    R.ANTICIPATED_DIRECT_COSTS,
    R.ANTICIPATED_F_AND_A_COSTS,
    R.TOTAL_ANTICIPATED_COSTS,
    R.START_BUDGET_PERIOD,
    R.END_BUDGET_PERIOD,
    CUSTOM.LIMITED_SUBMISSION_OPPORTUNITY
FROM
(
    SELECT
        SUM(P.ANTICIPATED_CHANGE_DIRECT) OVER (
            PARTITION BY P.AWARD_NUMBER,
                         Q.CLOSING_TRANS_CD
            ORDER BY P.TRANSACTION_ID
        ) AS ANTICIPATED_CHANGE_DIRECT,

        SUM(P.ANTICIPATED_CHANGE_INDIRECT) OVER (
            PARTITION BY P.AWARD_NUMBER,
                         Q.CLOSING_TRANS_CD
            ORDER BY P.TRANSACTION_ID
        ) AS ANTICIPATED_CHANGE_INDIRECT,

        P.ANTICIPATED_TOTAL_DIRECT,
        P.ANTICIPATED_TOTAL_INDIRECT,
        P.OBLIGATED_TOTAL_DIRECT,
        P.OBLIGATED_TOTAL_INDIRECT,
        P.VER_NBR,
        P.TNM_DOCUMENT_NUMBER,
        P.AWARD_AMOUNT_INFO_ID,
        P.AWARD_ID,
        P.AWARD_NUMBER,
        P.SEQUENCE_NUMBER,
        P.ANTICIPATED_TOTAL_AMOUNT,
        P.ANT_DISTRIBUTABLE_AMOUNT,
        P.OBLI_DISTRIBUTABLE_AMOUNT,
        P.TRANSACTION_ID,
        P.ENTRY_TYPE,
        P.EOM_PROCESS_FLAG,
        P.UPDATE_USER,

        SUM(P.ANTICIPATED_CHANGE) OVER (
            PARTITION BY P.AWARD_NUMBER,
                         Q.CLOSING_TRANS_CD
            ORDER BY P.TRANSACTION_ID
        ) AS ANTICIPATED_CHANGE,

        SUM(P.OBLIGATED_CHANGE) OVER (
            PARTITION BY P.AWARD_NUMBER,
                         Q.CLOSING_TRANS_CD
            ORDER BY P.TRANSACTION_ID
        ) AS OBLIGATED_CHANGE,

        SUM(P.OBLIGATED_CHANGE_DIRECT) OVER (
            PARTITION BY P.AWARD_NUMBER,
                         Q.CLOSING_TRANS_CD
            ORDER BY P.TRANSACTION_ID
        ) AS OBLIGATED_CHANGE_DIRECT,

        SUM(P.OBLIGATED_CHANGE_INDIRECT) OVER (
            PARTITION BY P.AWARD_NUMBER,
                         Q.CLOSING_TRANS_CD
            ORDER BY P.TRANSACTION_ID
        ) AS OBLIGATED_CHANGE_INDIRECT,

        P.OBJ_ID,
        P.ORIGINATING_AWARD_VERSION,
        P.AMOUNT_OBLIGATED_TO_DATE,
        P.FINAL_EXP_DATE,
        P.CUR_FUND_EFEC_DATE,
        P.OBLI_EXP_DATE,
        P.UPDATE_TIMESTAMP,
        P.TRANSACTION_TYPE_CODE,
        P.TNMCREATEDON,
        P.ANTICIPATED_DIRECT_COSTS,
        P.ANTICIPATED_F_AND_A_COSTS,
        P.TOTAL_ANTICIPATED_COSTS,
        P.START_BUDGET_PERIOD,
        P.END_BUDGET_PERIOD,
        Q.CLOSING_TRANS_CD AS ROLLUP_TRANS_CD

    FROM SAPBWKCRM.AAI_AAT_MAXSEQ_ROLLUP P
    JOIN TEMP_TAB Q
      ON P.AWARD_NUMBER = Q.AWARD_NUMBER

    WHERE P.TRANSACTION_ID BETWEEN Q.TRANSACTION_ID
                               AND Q.CLOSING_TRANS_CD
      AND P.TRANSACTION_TYPE_CODE NOT IN
          (6, 7, 9, 10, 13, 14, 15, 16)
) R

JOIN TEMP_TAB_S S
  ON S.AWARD_NUMBER = R.AWARD_NUMBER
 AND R.ROLLUP_TRANS_CD = R.TRANSACTION_ID

LEFT JOIN SAPBWKCRM.AWARD_CUSTOM_DATA CUSTOM
  ON CUSTOM.AWARD_ID = R.AWARD_ID

UNION

SELECT
    P.ANTICIPATED_CHANGE_DIRECT,
    P.ANTICIPATED_CHANGE_INDIRECT,
    P.ANTICIPATED_TOTAL_DIRECT,
    P.ANTICIPATED_TOTAL_INDIRECT,
    S.OBLIGATED_TOTAL_DIRECT,
    S.OBLIGATED_TOTAL_INDIRECT,
    P.VER_NBR,
    P.TNM_DOCUMENT_NUMBER,
    P.AWARD_AMOUNT_INFO_ID,
    P.AWARD_ID,
    P.AWARD_NUMBER,
    P.SEQUENCE_NUMBER,
    P.ANTICIPATED_TOTAL_AMOUNT,
    P.ANT_DISTRIBUTABLE_AMOUNT,
    P.OBLI_DISTRIBUTABLE_AMOUNT,
    P.TRANSACTION_ID,
    P.ENTRY_TYPE,
    P.EOM_PROCESS_FLAG,
    P.UPDATE_USER,
    P.ANTICIPATED_CHANGE,
    P.OBLIGATED_CHANGE,
    P.OBLIGATED_CHANGE_DIRECT,
    P.OBLIGATED_CHANGE_INDIRECT,
    P.OBJ_ID,
    P.ORIGINATING_AWARD_VERSION,
    S.AMOUNT_OBLIGATED_TO_DATE,
    S.FINAL_EXP_DATE,
    P.CUR_FUND_EFEC_DATE,
    P.OBLI_EXP_DATE,
    P.UPDATE_TIMESTAMP,
    P.TRANSACTION_TYPE_CODE,
    P.TNMCREATEDON,
    P.ANTICIPATED_DIRECT_COSTS,
    P.ANTICIPATED_F_AND_A_COSTS,
    P.TOTAL_ANTICIPATED_COSTS,
    P.START_BUDGET_PERIOD,
    P.END_BUDGET_PERIOD,
    CUSTOM.LIMITED_SUBMISSION_OPPORTUNITY

FROM SAPBWKCRM.AAI_AAT_MAXSEQ_ROLLUP P

JOIN TEMP_TAB_S S
  ON S.AWARD_NUMBER = P.AWARD_NUMBER

LEFT OUTER JOIN TEMP_TAB_TRAN_ID TRAN
  ON P.AWARD_NUMBER = TRAN.AWARD_NUMBER
 AND P.TRANSACTION_ID = TRAN.TRANSACTION_ID

LEFT JOIN SAPBWKCRM.AWARD_CUSTOM_DATA CUSTOM
  ON CUSTOM.AWARD_ID = P.AWARD_ID

WHERE TRAN.TRANSACTION_ID IS NULL
;
