-- SAPBWKCRM.AWARDS_MAXSEQ
--
-- ENHC2008944 added LIMITED_SUBMISSION_OPPORTUNITY as the last column (113),
-- VARCHAR2(1), sourced from SAPBWKCRM.AWARD_CUSTOM_DATA via the CUSTOM join
-- that this view already had. Nothing else changed - the ENHC2008944 deploy
-- was a single added line.
--
-- PREAWARD_DEPT_ADMIN_NAME and PREAWARD_DEPT_ADMIN_EMAIL (columns 111 and 112)
-- and the PDA subquery that feeds them are earlier work and are still here.
--
-- This is the deployed production text, read from DBA_VIEWS on 2026-09-11.
-- Everything below the CREATE line is verbatim. Do not reformat it - the point
-- of this file is that it matches production exactly.

CREATE OR REPLACE VIEW SAPBWKCRM.AWARDS_MAXSEQ AS
SELECT
  A.TRANSACTION_TYPE_CODE,
  CASE
    WHEN CUSTOM.CREDIT_OVERRIDE IS NOT NULL
      THEN CUSTOM.CREDIT_OVERRIDE
    ELSE A.LEAD_UNIT_NUMBER
  END AS LEAD_UNIT_NUMBER,
  A.ACTIVITY_TYPE_CODE,
  A.AWARD_TYPE_CODE,
  A.PRIME_SPONSOR_CODE,
  CFDA.CFDA_NUMBER,
  A.METHOD_OF_PAYMENT_CODE,
  A.DFAFS_NUMBER,
  A.PRE_AWARD_AUTHORIZED_AMOUNT,
  A.PROCUREMENT_PRIORITY_CODE,
  A.PROPOSAL_NUMBER,
  A.SPECIAL_EB_RATE_OFF_CAMPUS,
  A.SPECIAL_EB_RATE_ON_CAMPUS,
  A.SUB_PLAN_FLAG,
  CAST(REGEXP_REPLACE(A.TITLE, '[^[:print:]]', ' ') AS VARCHAR2(200)) AS "TITLE",
  A.VER_NBR,
  A.UPDATE_USER,
  A.PRE_AWARD_IN_AUTHORIZED_AMOUNT,
  A.ARCHIVE_LOCATION,
  A.BASIS_OF_PAYMENT_CODE,
  A.AWARD_ID,
  A.DOCUMENT_NUMBER,
  A.AWARD_NUMBER,
  A.SEQUENCE_NUMBER,
  A.SPONSOR_CODE,
  ROLODEX.COUNTRY_CODE AS "SPONSOR_COUNTRY_CD",
  CAST(REGEXP_REPLACE(CNTRY.POSTAL_CNTRY_NM_V3, '[^[:print:]]', ' ') AS VARCHAR2(255)) AS "SPONSOR_COUNTRY_NAME",
  A.STATUS_CODE,
  A.TEMPLATE_CODE,
  A.ACCOUNT_NUMBER,
  A.APPRVD_EQUIPMENT_INDICATOR,
  A.APPRVD_FOREIGN_TRIP_INDICATOR,
  A.APPRVD_SUBCONTRACT_INDICATOR,
  A.COST_SHARING_INDICATOR,
  A.IDC_INDICATOR,
  A.MODIFICATION_NUMBER,
  NSF.NSF_CODE,
  A.PAYMENT_SCHEDULE_INDICATOR,
  A.SCIENCE_CODE_INDICATOR,
  A.SPECIAL_REVIEW_INDICATOR,
  A.SPONSOR_AWARD_NUMBER,
  A.TRANSFER_SPONSOR_INDICATOR,
  A.ACCOUNT_TYPE_CODE,
  A.OBJ_ID,
  AE.PROPOSED_INDICATOR,
  A.FIN_ACCOUNT_DOC_NBR,
  AE.CHILD_TYPE,
  AE.MAJOR_PROJECT,
  AE.A133_CLUSTER,
  AE.ARRA_CODE,
  AE.AVC_INDICATOR,
  AE.FRINGE_NOT_ALLOWED_INDICATOR,
  AE.INTEREST_EARNED,
  AE.INTEREST_EARNED_ACCOUNT_NUMBER,
  AE.FEDERAL_RATE_DATE,
  AE.BU_BMC_FA_SPLIT,
  AE.CONFERENCE_GRANT,
  AE.PROGRAM_INCOME,
  AE.STOCK_AWARD,
  AE.FOREIGN_CURRENCY_AWARD,
  AE.CHILD_DESCRIPTION,
  AE.CLINICAL_TRIAL_INITIATED_BY,
  AE.IND_IDE_RESPONSIBILITY,
  AE.SPUDS_RECORD_NUMBER,
  AE.WALKER_SOURCE_NUMBER,
  AE.PRIME_SPONSOR_AWARD_ID,
  TO_CHAR(A.FIN_ACCOUNT_CREATION_DATE, 'yyyymmdd') AS FIN_ACCOUNT_CREATION_DATE,
  TO_CHAR(AE.CLINICAL_TRIAL_REG_DATE, 'yyyymmdd') AS CLINICAL_TRIAL_REG_DATE,
  TO_CHAR(AE.NCE_NOTIFICATION_DATE, 'yyyymmdd') AS NCE_NOTIFICATION_DATE,
  TO_CHAR(AE.LAST_TRANS_DATE, 'yyyymmdd') AS LAST_TRANS_DATE,
  TO_CHAR(A.AWARD_EXECUTION_DATE, 'yyyymmdd') AS AWARD_EXECUTION_DATE,
  TO_CHAR(A.AWARD_EFFECTIVE_DATE, 'yyyymmdd') AS AWARD_EFFECTIVE_DATE,
  TO_CHAR(A.PRE_AWARD_INST_EFFECTIVE_DATE, 'yyyymmdd') AS PRE_AWARD_INST_EFFECTIVE_DATE,
  TO_CHAR(A.PRE_AWARD_EFFECTIVE_DATE, 'yyyymmdd') AS PRE_AWARD_EFFECTIVE_DATE,
  TO_CHAR(A.UPDATE_TIMESTAMP, 'yyyymmdd') AS UPDATE_TIMESTAMP,
  TO_CHAR(A.NOTICE_DATE, 'yyyymmdd') AS NOTICE_DATE,
  TO_CHAR(A.CLOSEOUT_DATE, 'yyyymmdd') AS CLOSEOUT_DATE,
  TO_CHAR(A.AWARD_EFFECTIVE_DATE, 'yyyymmdd') AS BEGIN_DATE,
  CUSTOM.CREDIT_OVERRIDE,
  CUSTOM.INT_RESEARCH_IND,
  CUSTOM.PRIME_TRAVEL_IND,
  CUSTOM.INT_EFFORT_PCT,
  CUSTOM.INT_CNTRY_NAME,
  CUSTOM.HIRE_STAFF_IND,
  CUSTOM.EMP_CONTRACT_IND,
  CUSTOM.EMPLOYEE_IND,
  CUSTOM.CONTRACTOR_IND,
  CUSTOM.RENT_LEASE_IND,
  CUSTOM.INT_EXPENSE_IND,
  CUSTOM.INT_BANK_IND,
  CUSTOM.INT_HUMAN_IND,
  CUSTOM.PRE_DOC_IND,
  CUSTOM.POST_DOC_IND,
  CUSTOM.OPP_TITLE,
  CUSTOM.BILLING_AGMT,
  CUSTOM.OPP_NUM,
  CUSTOM.ACTV_CODE,
  CUSTOM.AUDITED,
  TO_CHAR(CUSTOM.RETENTION_DT, 'yyyymmdd') AS RETENTION_DT,
  CUSTOM.EXPORT_CONTRL,
  CUSTOM.INFO_SECURITY_COMPLIANCE,
  CUSTOM.COVID19_RESEARCH_IND,
  CUSTOM.TRUMP_EXEC_ORDER_CERT,
  CUSTOM.TRUMP_EXEC_ORDER_CERT_DET,
  CUSTOM.GRANT_TERMINATION,
  C.UNIT_NUMBER AS SECONDARY_AWARD_FUND_CENTER,
  C.AWARD_PERSON_UNIT_ID,
  FNA.ANTICIPATED_DIRECT_COST,
  FNA.ANTICIPATED_F_AND_A_COSTS,
  FNA.TOTAL_ANTICIPATED_COSTS,
  PDA.PROPOSAL_CONTACT_NAME AS PREAWARD_DEPT_ADMIN_NAME,
  PDA.PROPOSAL_CONTACT_EMAIL AS PREAWARD_DEPT_ADMIN_EMAIL,
  CUSTOM.LIMITED_SUBMISSION_OPPORTUNITY
FROM KCOEUS.AWARD A
INNER JOIN SAPBWKCRM.AWARDS_MAXSEQ_UNIQUE UNIQ
  ON UNIQ.AWARD_ID = A.AWARD_ID
LEFT JOIN (
  SELECT
    AWARD_ID,
    MIN(AWARD_CFDA_ID) AS MIN_CFDA_ID
  FROM KCOEUS.AWARD_CFDA
  GROUP BY AWARD_ID
) MINC
  ON MINC.AWARD_ID = A.AWARD_ID
LEFT JOIN KCOEUS.AWARD_CFDA CFDA
  ON CFDA.AWARD_CFDA_ID = MINC.MIN_CFDA_ID
LEFT JOIN KCOEUS.NSF_CODES NSF
  ON NSF.NSF_SEQUENCE_NUMBER = A.NSF_SEQUENCE_NUMBER
LEFT JOIN KCOEUS.AWARD_EXTENSION AE
  ON AE.AWARD_ID = A.AWARD_ID
LEFT JOIN SAPBWKCRM.AWARD_CUSTOM_DATA CUSTOM
  ON CUSTOM.AWARD_ID = A.AWARD_ID
LEFT JOIN KCOEUS.ROLODEX ROLODEX
  ON ROLODEX.ROLODEX_ID = A.SPONSOR_CODE
LEFT JOIN KCOEUS.KRLC_CNTRY_T CNTRY
  ON CNTRY.ALT_POSTAL_CNTRY_CD = ROLODEX.COUNTRY_CODE
LEFT JOIN (
  SELECT
    U.AWARD_PERSON_UNIT_ID,
    U.UNIT_NUMBER,
    A.AWARD_NUMBER,
    A.AWARD_ID
  FROM KCOEUS.AWARD_PERSONS A
  INNER JOIN KCOEUS.AWARD_PERSON_UNITS U
    ON U.AWARD_PERSON_ID = A.AWARD_PERSON_ID
  WHERE U.LEAD_UNIT_FLAG = 'N'
    AND A.CONTACT_ROLE_CODE = 'PI'
) C
  ON C.AWARD_ID = A.AWARD_ID
LEFT JOIN (
  SELECT
    X.AWARD_ID,
    X.PROPOSAL_CONTACT_NAME,
    X.PROPOSAL_CONTACT_EMAIL
  FROM (
    SELECT
      AFP.AWARD_ID,
      PDA.PROPOSAL_CONTACT_NAME,
      PDA.PROPOSAL_CONTACT_EMAIL,
      ROW_NUMBER() OVER (
        PARTITION BY AFP.AWARD_ID
        ORDER BY P.SEQUENCE_NUMBER DESC, P.PROPOSAL_ID DESC
      ) AS RN
    FROM KCOEUS.AWARD_FUNDING_PROPOSALS AFP
    LEFT JOIN KCOEUS.PROPOSAL P
      ON P.PROPOSAL_ID = AFP.PROPOSAL_ID
    LEFT JOIN SAPBWKCRM.V_PROPOSAL_PREAWARD_ADMIN PDA
      ON PDA.PROPOSAL_ID = P.PROPOSAL_ID
     AND PDA.SEQUENCE_NUMBER = P.SEQUENCE_NUMBER
  ) X
  WHERE X.RN = 1
) PDA
  ON PDA.AWARD_ID = A.AWARD_ID
LEFT JOIN (
  SELECT
    AWARD_ID,
    SUM(DIRECT_COST) AS ANTICIPATED_DIRECT_COST,
    SUM(INDIRECT_COST) AS ANTICIPATED_F_AND_A_COSTS,
    SUM(DIRECT_COST) + SUM(INDIRECT_COST) AS TOTAL_ANTICIPATED_COSTS
  FROM KCOEUS.AWARD_AMT_FNA_DISTRIBUTION
  GROUP BY AWARD_ID
) FNA
  ON FNA.AWARD_ID = A.AWARD_ID
;
